-- MySQL Script generated by MySQL Workbench
-- Sun Dec 17 19:39:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `age` INT NULL,
  `home` VARCHAR(20) NULL,
  `comment` TEXT(50) NULL,
  `vip` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  FULLTEXT INDEX (comment))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `from_city` VARCHAR(20) NULL,
  `to_city` VARCHAR(20) NULL,
  `cost` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`airline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`airline` ;

CREATE TABLE IF NOT EXISTS `mydb`.`airline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `rank` VARCHAR(5) NULL,
  `home` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`card` ;

CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_limit` INT NULL,
  `rank` VARCHAR(5) NULL,
  `bank_name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`main`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`main` ;

CREATE TABLE IF NOT EXISTS `mydb`.`main` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paid` TINYINT NULL DEFAULT 0,
  `client_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `airline_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_main_client_idx` (`client_id` ASC),
  INDEX `fk_main_ticket1_idx` (`ticket_id` ASC),
  INDEX `fk_main_airline1_idx` (`airline_id` ASC),
  INDEX `fk_main_card1_idx` (`card_id` ASC),
  CONSTRAINT `fk_main_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_main_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `mydb`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_main_airline1`
    FOREIGN KEY (`airline_id`)
    REFERENCES `mydb`.`airline` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_main_card1`
    FOREIGN KEY (`card_id`)
    REFERENCES `mydb`.`card` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
